### ISSUE TITLE
Supermarket incorrectly redirects Berkshelf clients to http://servername:443

### ISSUE THREAD

**Issue by irvingpop** [opscode/supermarket#967]
Using Supermarket 1.5.0 alpha (via Omnibus),  `knife supermarket download` works just fine but `berks install` fails. 

With a Berksfile that looks like:
```ruby
source "https://default-centos-66.vagrantup.com/"
cookbook 'audit'
```

It successfully contacts the /universe endpoint,  but then talks HTTP to port 443 to get the `/api/v1/cookbooks` endpoint:
```
2015/01/14 19:31:47 [info] 23679#0: *3 client sent plain HTTP request to HTTPS port while reading client request headers, client: 33.33.33.1, server: default-centos-66.vagrantup.com, request: "GET /api/v1/cookbooks/audit/versions/0_1_3 HTTP/1.1", host: "default-centos-66.vagrantup.com:443"
```

Berkshelf debug output shows:

```
I, [2015-01-14T11:31:46.913372 #15416]  INFO -- : Installing audit (0.1.3)
D, [2015-01-14T11:31:46.913633 #15416] DEBUG -- :   Downloading audit (0.1.3) from https://default-centos-66.vagrantup.com/
D, [2015-01-14T11:31:46.913817 #15416] DEBUG -- :     => #<Berkshelf::APIClient::RemoteCookbook:0x007f9b60a51290 @name="audit", @version="0.1.3", @attributes=#<Hashie::Mash dependencies=#<Hashie::Mash> download_url="http://default-centos-66.vagrantup.com:443/api/v1/cookbooks/audit/versions/0.1.3/download" location_path="http://default-centos-66.vagrantup.com:443/api/v1" location_type="opscode">>
Installing audit (0.1.3) from https://default-centos-66.vagrantup.com/ ([opscode] http://default-centos-66.vagrantup.com:443/api/v1)
D, [2015-01-14T11:31:46.916601 #15416] DEBUG -- : ==> Chef response did not contain a JSON body
E, [2015-01-14T11:31:46.916778 #15416] ERROR -- : Actor crashed!
Berkshelf::CommunitySiteError: An unexpected error occurred retrieving 'audit' (0.1.3) from the cookbook site at ''.
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/community_rest.rb:127:in `find'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/community_rest.rb:103:in `download'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:62:in `try_download'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:36:in `block in download'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `each'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `download'
	/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:105:in `install'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'

```

**Comment by leftathome** [comment]
Confirmed on my install, universe.json is being generated with http:...:443 URLs.  I'll see if I can figure out a fix since I'm hoping to launch the internal site by Friday...

**Comment by leftathome** [comment]
Couple things seem to be going on here.

For starters, Universe/UniverseCache key off of the incoming protocol and use it to build _and cache_ the universe.json response.  Public Supermarket seems to do the right thing (http visitors get the version that has http URLs, https visitors get the version with https URLs).  Privatized behind-a-load-balancer Supermarkets, which do all their talking in HTTP but are supposed to serve nothing-but-HTTPS URLs, will always return the 'http' universe.

Other URLs in the API also appear broken.  It looks like they're pulling from the Rails environment inherited by ActiveController itself.  I'm not sure if there's a more proper way to do it, but adding a stanza to `config/application.rb` pointing to `action_controller` instead of `action_mailer` and setting the protocol/host/port info seems to have fixed the URLs returned by the API.

Removing UniverseCache ( ... yeah, not best practice!) from the call to /universe and forcing the protocol to be generated as 'https' seems to be generating proper universe URLs.

I've also brutalized in an /api/v1/users endpoint just so I can occasionally query it and see who's signed up.  I was hoping to launch with a pretty user directory but for some reason I can't get UsersController#index to render (even though it's routing ... maybe I should stick to Sinatra apps? :D ).

Things look good for me, though I do have one user complaining that he's somehow getting an http-to-https redirect error from Berkshelf when he adds our internal Supermarket to his source list.  It's a big head scratcher for me because I know the app isn't serving any more HTTP URLs.
